default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_tudu_development

test:
  <<: *default
  database: kiosk_tudu_test

production:
  <<: *default
  database: kiosk_tudu_production
  username: <%= ENV.fetch("KIOSK_TUDU_DB_USER", "kiosk_tudu") %>
  password: <%= ENV["KIOSK_TUDU_DB_PASSWORD"] %>
