default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_atablefor_development

test:
  <<: *default
  database: kiosk_atablefor_test

production:
  <<: *default
  database: kiosk_atablefor_production
  username: <%= ENV.fetch("KIOSK_ATABLEFOR_DB_USER", "kiosk_atablefor") %>
  password: <%= ENV["KIOSK_ATABLEFOR_DB_PASSWORD"] %>
