source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# --- Kiosk ----------------------------------------------------------------
gem "kiosk-all",        path: "../kiosk-all"
gem "kiosk-core",       path: "../kiosk-core"
gem "kiosk-rls",        path: "../kiosk-rls"
gem "kiosk-server",       path: "../kiosk-server"
gem "kiosk-pow-equihash", path: "../kiosk-pow-equihash"
gem "kiosk-reputation",   path: "../kiosk-reputation"
gem "kiosk-redteam",      path: "../kiosk-redteam"
gem "kiosk-pay-stripe",   path: "../kiosk-pay-stripe"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
