default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_stylish_development

test:
  <<: *default
  database: kiosk_stylish_test

production:
  <<: *default
  database: kiosk_stylish_production
  username: <%= ENV.fetch("KIOSK_STYLISH_DB_USER", "kiosk_stylish") %>
  password: <%= ENV["KIOSK_STYLISH_DB_PASSWORD"] %>
