default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_skooti_development

test:
  <<: *default
  database: kiosk_skooti_test

production:
  <<: *default
  database: <%= ENV.fetch("KIOSK_SKOOTI_DB", "kiosk_skooti_production") %>
  username: <%= ENV.fetch("KIOSK_SKOOTI_DB_USER", "kiosk_skooti") %>
  password: <%= ENV["KIOSK_SKOOTI_DB_PASSWORD"] %>
