default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_saas_booking_development

test:
  <<: *default
  database: kiosk_saas_booking_test

production:
  <<: *default
  database: kiosk_saas_booking_production
  username: <%= ENV.fetch("KIOSK_SAAS_BOOKING_DB_USER", "kiosk_saas_booking") %>
  password: <%= ENV["KIOSK_SAAS_BOOKING_DB_PASSWORD"] %>
