default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

development:
  <<: *default
  database: kiosk_demo_development

test:
  <<: *default
  database: kiosk_demo_test

production:
  <<: *default
  database: kiosk_demo_production
  username: <%= ENV.fetch("KIOSK_DEMO_DB_USER", "kiosk_demo") %>
  password: <%= ENV["KIOSK_DEMO_DB_PASSWORD"] %>
